# Generated by Django 5.1 on 2024-08-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='player_tracker.team'),
        ),
        migrations.DeleteModel(
            name='MatchStats',
        ),
    ]
